/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminItemsRouteImport } from './routes/_authenticated/admin/items'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin/stock'
import { Route as AuthenticatedAdminSyncLogRouteImport } from './routes/_authenticated/admin/sync-log'
import { Route as AuthenticatedAdminWarehousesRouteImport } from './routes/_authenticated/admin/warehouses'
import { Route as ApiPublicHooksSyncStockRouteImport } from './routes/api/public/hooks/sync-stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminItemsRoute = AuthenticatedAdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/admin/stock',
  path: '/admin/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSyncLogRoute =
  AuthenticatedAdminSyncLogRouteImport.update({
    id: '/admin/sync-log',
    path: '/admin/sync-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWarehousesRoute =
  AuthenticatedAdminWarehousesRouteImport.update({
    id: '/admin/warehouses',
    path: '/admin/warehouses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSyncStockRoute = ApiPublicHooksSyncStockRouteImport.update({
  id: '/api/public/hooks/sync-stock',
  path: '/api/public/hooks/sync-stock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/sync-log': typeof AuthenticatedAdminSyncLogRoute
  '/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/sync-log': typeof AuthenticatedAdminSyncLogRoute
  '/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin/items': typeof AuthenticatedAdminItemsRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/sync-log': typeof AuthenticatedAdminSyncLogRoute
  '/_authenticated/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/items'
    | '/admin/stock'
    | '/admin/sync-log'
    | '/admin/warehouses'
    | '/api/public/hooks/sync-stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/items'
    | '/admin/stock'
    | '/admin/sync-log'
    | '/admin/warehouses'
    | '/api/public/hooks/sync-stock'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin/items'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/sync-log'
    | '/_authenticated/admin/warehouses'
    | '/api/public/hooks/sync-stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiPublicHooksSyncStockRoute: typeof ApiPublicHooksSyncStockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/items': {
      id: '/_authenticated/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AuthenticatedAdminItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/admin/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sync-log': {
      id: '/_authenticated/admin/sync-log'
      path: '/admin/sync-log'
      fullPath: '/admin/sync-log'
      preLoaderRoute: typeof AuthenticatedAdminSyncLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/warehouses': {
      id: '/_authenticated/admin/warehouses'
      path: '/admin/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AuthenticatedAdminWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-stock': {
      id: '/api/public/hooks/sync-stock'
      path: '/api/public/hooks/sync-stock'
      fullPath: '/api/public/hooks/sync-stock'
      preLoaderRoute: typeof ApiPublicHooksSyncStockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminItemsRoute: typeof AuthenticatedAdminItemsRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminSyncLogRoute: typeof AuthenticatedAdminSyncLogRoute
  AuthenticatedAdminWarehousesRoute: typeof AuthenticatedAdminWarehousesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminItemsRoute: AuthenticatedAdminItemsRoute,
  AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
  AuthenticatedAdminSyncLogRoute: AuthenticatedAdminSyncLogRoute,
  AuthenticatedAdminWarehousesRoute: AuthenticatedAdminWarehousesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiPublicHooksSyncStockRoute: ApiPublicHooksSyncStockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
