/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as ApiPublicHooksSyncStockRouteImport } from './routes/api/public/hooks/sync-stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncStockRoute = ApiPublicHooksSyncStockRouteImport.update({
  id: '/api/public/hooks/sync-stock',
  path: '/api/public/hooks/sync-stock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/warehouses': typeof WarehousesRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/warehouses': typeof WarehousesRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/warehouses': typeof WarehousesRoute
  '/api/public/hooks/sync-stock': typeof ApiPublicHooksSyncStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items' | '/warehouses' | '/api/public/hooks/sync-stock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items' | '/warehouses' | '/api/public/hooks/sync-stock'
  id:
    '__root__' | '/' | '/items' | '/warehouses' | '/api/public/hooks/sync-stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRoute
  WarehousesRoute: typeof WarehousesRoute
  ApiPublicHooksSyncStockRoute: typeof ApiPublicHooksSyncStockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-stock': {
      id: '/api/public/hooks/sync-stock'
      path: '/api/public/hooks/sync-stock'
      fullPath: '/api/public/hooks/sync-stock'
      preLoaderRoute: typeof ApiPublicHooksSyncStockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRoute,
  WarehousesRoute: WarehousesRoute,
  ApiPublicHooksSyncStockRoute: ApiPublicHooksSyncStockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
